services:
  app:
    build: ../scala
    container_name: scala_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
#    command: bash -c "ngrok http 9000 && sbt compile run"
    command: cat ngrok.yml