name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    name: Analyze golang project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: golang
          args: >
            -Dsonar.projectKey=krystian-sikora_e-biznes
            -Dsonar.organization=krystian-sikora
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}